DROP DATABASE IF EXISTS ZHOU_HU_USER;
CREATE DATABASE ZHOU_HU_USER;
USE ZHOU_HU_USER;
DROP TABLE IF EXISTS USER_INFO;
/*用户信息表*/
CREATE TABLE  USER_INFO(
	`ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `USERNAME` VARCHAR(30) NOT NULL COMMENT '登录的用户名',
    `PASSWORD` VARCHAR(30) NOT NULL COMMENT '用来登录的密码',
    `NICK_NAME` VARCHAR(30) NOT NULL COMMENT '昵称',
    `CREATED_TIME` DATETIME   NOT NULL COMMENT '注册时间',
    `UPDATED_TIME` VARCHAR(30) NOT NULL COMMENT '更新时间',
    `VERSION` BIGINT NOT NULL DEFAULT 0 COMMENT '版本号',
    `OBSOLETE` BIGINT NOT NULL DEFAULT 0 COMMENT '版本号'
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8

DROP DATABASE IF EXISTS ZHOU_HU_PRODUCTS;
CREATE DATABASE ZHOU_HU_PRODUCTS;
USE ZHOU_HU_PRODUCTS;
DROP TABLE IF EXISTS PRODUCTS;
/*商品表*/
CREATE TABLE `PRODUCT` (
  `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL COMMENT '商品标题',
  `PRICE` BIGINT NOT NULL COMMENT '商品价格单位为分' ,
  `CATEGORY` VARCHAR(40) NOT NULL COMMENT '商品种类' ,
  `PNUM` BIGINT NOT NULL COMMENT '商品数量',
  `IMG_URL` VARCHAR(100) COMMENT '图片地址',
  `DESC` VARCHAR(255) DEFAULT '' COMMENT '商品描述'
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8


CREATE TABLE `user` (
  `id` INT(11) AUTO_INCREMENT,
  `username` VARCHAR(20) ,
  `PASSWORD` VARCHAR(20) ,
  `gender` VARCHAR(10) ,
  `email` VARCHAR(50) ,
  `telephone` VARCHAR(20) ,
  `introduce` VARCHAR(100),
  `activeCode` VARCHAR(50) ,
  `state` INT(11) ,
  `role` VARCHAR(10) DEFAULT '普通用户',
  `registTime` TIMESTAMP ,
  PRIMARY KEY (`id`)
)

订单表
CREATE TABLE `orders` (
  `id` VARCHAR(100) ,
  `money` DOUBLE ,
  `receiverAddress` VARCHAR(255) ,
  `receiverName` VARCHAR(20) ,
  `receiverPhone` VARCHAR(20) ,
  `paystate` INT(11) ,
  `ordertime` TIMESTAMP ,
  `user_id` INT(11) ,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`user_id`) REFERENCES `user` (`id`)
)
订单项表
CREATE TABLE `orderitem` (
  `order_id` VARCHAR(100) ,
  `product_id` VARCHAR(100),
  `buynum` INT(11) ,
  PRIMARY KEY (`order_id`,`product_id`),
  FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`),
  FOREIGN KEY (`product_id`) REFERENCES `products` (`id`)
)